SELECT 
C.CODI_EMP CODI_LOJA,
T.CODI_TRA CODI_CLIENTE,
T.RAZA_TRA NOME_CLIENTE, 
CASE T.TJUR_TRA 
	WHEN 'J' THEN regexp_replace(LPAD(T.CGC_TRA, 14, '0'),'([0-9]{2})([0-9]{3})([0-9]{3})([0-9]{4})([0-9]{2})','\1.\2.\3/\4-\5')
	WHEN 'F' THEN regexp_replace(LPAD(T.CGC_TRA, 11, '0'), '([0-9]{3})([0-9]{3})([0-9]{3})([0-9]{2})','\1.\2.\3-\4')
END AS CPF_CNPJ,
T.TEL1_TRA FONE,
C.RGCO_CLI ||' - '||C.OECO_CLI RG,
T.CEND_TRA END_COBRANCA,
M.DESC_MUN CIDADE_COBRANCA,
M.ESTA_MUN UF_COBRANCA,
T.SITU_TRA SITU_CLIENTE,
C.COD1_PES AS CODI_CTV_VENDEDOR
FROM TRANSAC T
LEFT JOIN CLIENTE C ON C.CODI_TRA = T.CODI_TRA 
LEFT JOIN MUNICIPIO M ON M.CODI_MUN = T.CODI_MUN
WHERE CLIE_TRA = 'S'
ORDER BY 1