SELECT 
T.CODI_TRA CODI_FORN,
T.RAZA_TRA NOME_FORN, 
CASE T.TJUR_TRA 
	WHEN 'J' THEN regexp_replace(LPAD(T.CGC_TRA, 14, '0'),'([0-9]{2})([0-9]{3})([0-9]{3})([0-9]{4})([0-9]{2})','\1.\2.\3/\4-\5')
	WHEN 'F' THEN regexp_replace(LPAD(T.CGC_TRA, 11, '0'), '([0-9]{3})([0-9]{3})([0-9]{3})([0-9]{2})','\1.\2.\3-\4')
END AS CPF_CNPJ,
T.TEL1_TRA FONE,
T.CEND_TRA END_COBRANCA,
M.DESC_MUN CIDADE_COBRANCA,
M.ESTA_MUN UF_COBRANCA,
T.SITU_TRA SITU_FORN
FROM TRANSAC T
LEFT JOIN MUNICIPIO M ON M.CODI_MUN = T.CODI_MUN
WHERE T.FORN_TRA  = 'S'
ORDER BY 1