SELECT G.CODI_GPR CODI_GRUPO, G.DESC_GPR GRUPO, G.SITU_GPR SITU_GRUPO, S.CODI_SBG CODI_SUBGRUPO, S.DESC_SBG SUBGRUPO
FROM GRUPO G
LEFT JOIN SUBGRUPO S ON G.CODI_GPR = S.CODI_GPR
WHERE G.CODI_GPR IN (1,2,3,4,5) -- VERIFICAR OS GRUPOS QUE VAI SER UTILIZADO
ORDER BY 1