SELECT c.CODI_EMP CODI_LOJA, c.IDEN_EMP NOME_LOJA, c.CODI_MUN, m.DESC_MUN "MUNICIPIO", c.CNPJ_EMP, 
c.INE_EMP "INSC_ESTADUAL"
FROM CADEMP c
LEFT JOIN MUNICIPIO m ON c.CODI_MUN = m.CODI_MUN
WHERE SITU_EMP = 'A'