SELECT 
PS.CODI_PSV CODI_PRODUTO,
PS.DESC_PSV PRODUTO,
PS.UNID_PSV UNID,
G.CODI_GPR CODI_GRUPO,
G.DESC_GPR GRUPO,
S.CODI_SBG CODI_SUBGRUPO,
S.DESC_SBG SUBGRUPO,
P.CODI_TRA CODI_FORNECEDOR,
T.RAZA_TRA FORNECEDOR,
PS.SITU_PSV SITU_PRODUTO
FROM PRODSERV PS
LEFT JOIN PRODUTO P ON P.CODI_PSV  = PS.CODI_PSV
LEFT JOIN TRANSAC T ON P.CODI_TRA = T.CODI_TRA
LEFT JOIN GRUPO G ON PS.CODI_GPR = G.CODI_GPR
LEFT JOIN SUBGRUPO S ON PS.CODI_GPR = S.CODI_GPR AND PS.CODI_SBG = S.CODI_SBG
WHERE PS.CODI_GPR IN (1,2,3,4,5,6,462) 
--AND PS.SITU_PSV = 'A'
ORDER BY 1