SELECT P.CODI_TRA CODI_PARCEIRO, T.RAZA_TRA PARCEIRO, T.SITU_TRA SITU_PARCEIRO, P.PROP_PRO CODI_PROPRIEDADE, P.DESC_PRO PROPRIEDADE, P.ENDE_PRO ENDERECO, P.BAIR_PRO BAIRRO,
P.ISNE_PRO INSCR_ESTADUAL, P.AREA_PRO AREA_PROPRIED,  M.DESC_MUN MUNICIPIO, P.SITU_PRO SITU_PROPRIED, V.COD1_PES CODI_CTV_VENDEDOR
FROM PROPRIED P
LEFT JOIN VENDEDORPROPRIED V ON P.PROP_PRO = V.PROP_PRO
LEFT JOIN TRANSAC T ON P.CODI_TRA = T.CODI_TRA 
LEFT JOIN MUNICIPIO M ON P.CODI_MUN = M.CODI_MUN
ORDER BY 1,3