SELECT P.CODI_PES CODI_PESSOAL, P.CODI_EMP CODI_EMPRESA, P.NOME_PES NOME_USUARIO, P.ENDE_PES ENDERECO, P.TELE_PES TELEFONE, P.EMAI_PES EMAIL, P.CPF_PES CPF, P.DNAS_PES DT_NASCIMENTO, 
P.CODI_CAR CODI_CARGO, C.DESC_CAR DESC_CARGO
FROM PESSOAL P
LEFT JOIN CARGO C ON P.CODI_CAR = C.CODI_CAR